Repository Flexberry/Flexberry.SpringBootBackend.Sample, pull requests merged in 2023-06, with the labels that each got.

#32 git attrs for mvnw.
  src/SpringBootBackend/.gitattributes
Labels: bug

#42 Документация по ElasticSearch и отправки в него метрик.
  docs/Отправка данных в Elasticsearch.md
Labels: documentation

#45 Подключить ElastickSearch в Grafana.
  src/Docker/Dockerfiles/GrafanaLoki/Dockerfile.Grafana
  src/Docker/Dockerfiles/GrafanaLoki/dashboard-config.yaml
  src/Docker/Dockerfiles/GrafanaLoki/dashboards/elasticsearch.json
  src/Docker/Dockerfiles/GrafanaLoki/datasource-config.yaml
Labels: enhancement

#44 Документация по отправке логов из бэкенда в loki
  docs/Отправка логов из бэкенда в loki.md
Labels: documentation

#49 Документации метрики.
  docs/images/metrics_db.png
  docs/Метрики Micrometer.md
  src/SpringBootBackend/pom.xml
  src/SpringBootBackend/src/main/java/net/flexberry/flexberrySampleSpring/registry/MetricRegistry.java
Labels: documentation

#52 ElasticSearch - синхронизация с БД Postgres.
  src/Docker/Dockerfiles/Dockerfile.Postgres
  src/Docker/Dockerfiles/GrafanaLoki/dashboards/elasticsearch.json
  src/Docker/Dockerfiles/GrafanaLoki/datasource-config.yaml
  src/Docker/Dockerfiles/PGSync/Dockerfile.PGSync
  src/Docker/Dockerfiles/PGSync/Dockerfile.Redis
  src/Docker/Dockerfiles/PGSync/PGSync/entrypoint.sh
  src/Docker/Dockerfiles/PGSync/PGSync/schema.json
  src/Docker/create-image.cmd
  src/Docker/docker-compose.yml
  src/SQL/Postgres/pgsync.sql
Labels: enhancement

#55 Документация - ElasticSearch (синхронизация с БД).
  docs/Синхронизация Elasticsearch с базой данных PostgreSQL.md
Labels: documentation

#54 Обновить Readme.
  README.md
  docs/images/common_schema.png
Labels: documentation
